[11:41:43] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 11:42:16: before drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 11:42:16: after drop huge graphs, there are 188 graphs in MUTAG
2022/03/31 11:42:16: ready to load the pre-computed wass distances
2022/03/31 11:42:16: after loading pre-computed wass distances, there are distance with w=[0.6] remained
2022/03/31 11:42:16: ready to generate node embeddings
/public1/home/scfa1517/HKS-Wasserstein-kernel/signature.py:99: ComplexWarning: Casting complex values to real discards the imaginary part
  wks[i] = np.array([np.sum(np.exp(-(e-log_eigenvalue)*(e-log_eigenvalue)/(2*sigma*sigma))*eigenvectors[i]*eigenvectors[i])/np.sum(np.exp(-(e-log_eigenvalue)*(e-log_eigenvalue)/(2*sigma*sigma))) for e in sample_points])
2022/03/31 11:43:18: the node embedding have been generated
2022/03/31 11:43:18: ready to compute the wass diss with sinkhorn = False and w = 0.6
2022/03/31 11:43:22: have computed the wass diss with sinkhorn = False and w = 0.6
2022/03/31 11:43:22: have saved wasserstein_distance_matrix_it0_0.60_False.npy
2022/03/31 11:43:22: Wasserstein distances computation done. Saved to file.
2022/03/31 11:43:22: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 11:43:22: gridsearch and crossvalidation done
[11:43:24] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 11:43:25: before drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 11:43:26: after drop huge graphs, there are 344 graphs in PTC_MR
2022/03/31 11:43:26: ready to load the pre-computed wass distances
2022/03/31 11:43:26: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 11:43:26: Wasserstein distances computation done. Saved to file.
2022/03/31 11:43:26: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 11:43:26: gridsearch and crossvalidation done
[11:43:27] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 11:43:28: before drop huge graphs, there are 600 graphs in ENZYMES
2022/03/31 11:43:28: after drop huge graphs, there are 600 graphs in ENZYMES
2022/03/31 11:43:28: ready to load the pre-computed wass distances
2022/03/31 11:43:28: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 11:43:28: Wasserstein distances computation done. Saved to file.
2022/03/31 11:43:28: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 11:43:29: gridsearch and crossvalidation done
[11:43:30] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 11:43:31: before drop huge graphs, there are 1113 graphs in PROTEINS
2022/03/31 11:43:31: after drop huge graphs, there are 1112 graphs in PROTEINS
2022/03/31 11:43:31: ready to load the pre-computed wass distances
2022/03/31 11:43:32: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 11:43:32: Wasserstein distances computation done. Saved to file.
2022/03/31 11:43:32: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 11:43:32: gridsearch and crossvalidation done
[11:43:33] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/31 11:43:35: before drop huge graphs, there are 1178 graphs in DD
2022/03/31 11:43:35: after drop huge graphs, there are 1126 graphs in DD
2022/03/31 11:43:35: ready to load the pre-computed wass distances
2022/03/31 11:43:35: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/31 11:43:35: Wasserstein distances computation done. Saved to file.
2022/03/31 11:43:35: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/31 11:43:35: gridsearch and crossvalidation done
