[23:30:00] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/28 11:30:18: before drop huge graphs, there are 1113 graphs in PROTEINS
2022/03/28 11:30:18: after drop huge graphs, there are 1112 graphs in PROTEINS
2022/03/28 11:30:18: ready to load the pre-computed wass distances
2022/03/28 11:30:18: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/28 11:30:18: Wasserstein distances computation done. Saved to file.
2022/03/28 11:30:18: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/28 11:30:19: gridsearch and crossvalidation done
[23:30:21] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/28 11:30:22: before drop huge graphs, there are 1113 graphs in PROTEINS
2022/03/28 11:30:22: after drop huge graphs, there are 1112 graphs in PROTEINS
2022/03/28 11:30:22: ready to load the pre-computed wass distances
2022/03/28 11:30:22: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/28 11:30:22: Wasserstein distances computation done. Saved to file.
2022/03/28 11:30:22: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/28 11:30:22: gridsearch and crossvalidation done
[23:30:24] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/28 11:30:25: before drop huge graphs, there are 1113 graphs in PROTEINS
2022/03/28 11:30:25: after drop huge graphs, there are 1112 graphs in PROTEINS
2022/03/28 11:30:25: ready to load the pre-computed wass distances
2022/03/28 11:30:25: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/28 11:30:25: Wasserstein distances computation done. Saved to file.
2022/03/28 11:30:25: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/28 11:30:25: gridsearch and crossvalidation done
[23:30:27] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/28 11:30:28: before drop huge graphs, there are 1113 graphs in PROTEINS
2022/03/28 11:30:28: after drop huge graphs, there are 1112 graphs in PROTEINS
2022/03/28 11:30:28: ready to load the pre-computed wass distances
2022/03/28 11:30:28: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/28 11:30:28: Wasserstein distances computation done. Saved to file.
2022/03/28 11:30:28: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/28 11:30:29: gridsearch and crossvalidation done
[23:30:30] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/28 11:30:31: before drop huge graphs, there are 1113 graphs in PROTEINS
2022/03/28 11:30:31: after drop huge graphs, there are 1112 graphs in PROTEINS
2022/03/28 11:30:31: ready to load the pre-computed wass distances
2022/03/28 11:30:31: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/28 11:30:31: Wasserstein distances computation done. Saved to file.
2022/03/28 11:30:31: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/28 11:30:31: gridsearch and crossvalidation done
[23:30:33] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/28 11:30:34: before drop huge graphs, there are 1113 graphs in PROTEINS
2022/03/28 11:30:34: after drop huge graphs, there are 1112 graphs in PROTEINS
2022/03/28 11:30:34: ready to load the pre-computed wass distances
2022/03/28 11:30:34: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/28 11:30:34: Wasserstein distances computation done. Saved to file.
2022/03/28 11:30:34: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/28 11:30:34: gridsearch and crossvalidation done
[23:30:36] /opt/dgl/src/runtime/tensordispatch.cc:43: TensorDispatcher: dlopen failed: /public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/dgl/tensoradapter/pytorch/libtensoradapter_pytorch_1.10.2.so: cannot open shared object file: No such file or directory
Using backend: pytorch
2022/03/28 11:30:37: before drop huge graphs, there are 1113 graphs in PROTEINS
2022/03/28 11:30:37: after drop huge graphs, there are 1112 graphs in PROTEINS
2022/03/28 11:30:37: ready to load the pre-computed wass distances
2022/03/28 11:30:37: after loading pre-computed wass distances, there are distance with w=[] remained
2022/03/28 11:30:37: Wasserstein distances computation done. Saved to file.
2022/03/28 11:30:37: Running SVMs, crossvalidation: True, gridsearch: False.
2022/03/28 11:30:37: gridsearch and crossvalidation done
