/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/grakel/kernels/kernel.py:201: RuntimeWarning: invalid value encountered in sqrt
  return km / np.sqrt(np.outer(self._X_diag, self._X_diag))
Traceback (most recent call last):
  File "/public1/home/scfa1517/HKS-Wasserstein-kernel/baselines/baselines.py", line 120, in <module>
    main()
  File "/public1/home/scfa1517/HKS-Wasserstein-kernel/baselines/baselines.py", line 101, in main
    gs, best_params,unit_result,param = utilities.custom_grid_search_cv(SVC(kernel='precomputed'), 
  File "/public1/home/scfa1517/HKS-Wasserstein-kernel/baselines/../utilities.py", line 40, in custom_grid_search_cv
    return ret_model.fit(precomputed_kernels[params[best_idx]['K_idx']], y), params[best_idx],fin_results,params
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 190, in fit
    X, y = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 964, in check_X_y
    X = check_array(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
/var/spool/slurm/d/job1122098/slurm_script: line 16: 105343 Killed                  python3 baselines.py -d DD -gs
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/grakel/kernels/graphlet_sampling.py:324: RuntimeWarning: invalid value encountered in true_divide
  return np.divide(km, np.sqrt(np.outer(self._X_diag, self._X_diag)))
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:770: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 761, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 216, in __call__
    return self._score(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 258, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 68, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 791, in predict
    y = super().predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 414, in predict
    X = self._validate_for_predict(X)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 592, in _validate_for_predict
    X = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 566, in _validate_data
    X = check_array(X, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

  warnings.warn(
Traceback (most recent call last):
  File "/public1/home/scfa1517/HKS-Wasserstein-kernel/baselines/baselines.py", line 120, in <module>
    main()
  File "/public1/home/scfa1517/HKS-Wasserstein-kernel/baselines/baselines.py", line 101, in main
    gs, best_params,unit_result,param = utilities.custom_grid_search_cv(SVC(kernel='precomputed'), 
  File "/public1/home/scfa1517/HKS-Wasserstein-kernel/baselines/../utilities.py", line 40, in custom_grid_search_cv
    return ret_model.fit(precomputed_kernels[params[best_idx]['K_idx']], y), params[best_idx],fin_results,params
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/svm/_base.py", line 190, in fit
    X, y = self._validate_data(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 964, in check_X_y
    X = check_array(
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/public1/home/scfa1517/anaconda3/envs/myenv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
